/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tigger_MafIoCtlAdapterJNI */

#ifndef _Included_tigger_MafIoCtlAdapterJNI
#define _Included_tigger_MafIoCtlAdapterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tigger_MafIoCtlAdapterJNI
 * Method:    ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tigger_MafIoCtlAdapterJNI_ioctl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
